### Path ###
typeset -U PATH path
path=($HOME/bin $HOME/.cargo/bin $HOME/.local/bin $path)
export PATH

### nvim
export EDITOR='nvim'
export TERMINAL='kitty'

### Python ###
export PYTHON_KEYRING_BACKEND='keyring.backends.null.Keyring'

### GTK ###
export GDK_SCALE='1'
export GDK_DPI_SCALE='1'

### qt ###
#export QT_QPA_PLATFORM='wayland'
export QT_QPA_PLATFORMTHEME='qt6ct'
#export QT_WAYLAND_DISABLE_WINDOWDECORATION='1'
#export QT_WAYLAND_FORCE_DPI='physical'
export QT_PLUGIN_PATH='/usr/lib/qt/plugins'

### fzf ###
export FZF_DEFAULT_COMMAND='rg'
export FZF_DEFAULT_OPTS='--ansi'

### nnn ###
export NNN_TRASH='1'
export NNN_PREVIEWDIR='$HOME/.cache/nnn/previews'
export NNN_PLUG='p:preview-tui'
export NNN_OPTS='aHxPp'

### kitty ###
unset KITTY_SHELL_INTEGRATION
